# Generated by Django 2.2.28 on 2023-03-04 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Pickup', 'Pickup'), ('Van', 'Van'), ('Coupe', 'Coupe'), ('Luxury', 'Luxury')], max_length=10)),
                ('license_plate_number', models.CharField(max_length=10)),
                ('max_num_of_passenger', models.PositiveIntegerField()),
                ('special_vehicle_info', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField(help_text='Format: 2023-03-01 12:00')),
                ('passenger_num', models.PositiveIntegerField(default=1)),
                ('allow_sharer', models.BooleanField(default=False)),
                ('special_request', models.CharField(blank=True, max_length=300)),
                ('vehicle_type', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Pickup', 'Pickup'), ('Van', 'Van'), ('Coupe', 'Coupe'), ('Luxury', 'Luxury')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('confirmed', 'confirmed'), ('complete', 'complete')], default='open', max_length=10)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rideDriver', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ManyToManyField(blank=True, related_name='sharers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['arrival_time'],
            },
        ),
    ]
